import Head from "next/head";
import styles from "@/styles/Home.module.css";
import AgendaScreen from "./AgendaScreen.tsx";
import { LinkCard } from "@/components/LinkCard/LinkCard.component";

export default function Home() {
  return (
    <>
      <Head>
        <title>BSport Agenda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ paddingBottom: 16 }} className={styles.description}>
          <p>
            Your&nbsp;
            <code className={styles.code}>BSport </code>
            Agenda
          </p>
          <div>
            <a
              href="https://github.com/HugoChollet"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Hugo
            </a>
          </div>
        </div>
        <AgendaScreen />
        <div style={{ paddingTop: 16 }} className={styles.grid}>
          <LinkCard
            link={"https://nextjs.org/docs?utm_source=create-next-app"}
            title="NextJS Docs"
            description="Find in-depth information about Next.js features and API."
          />
          <LinkCard
            link={"https://devexpress.github.io/devextreme-reactive/docs/"}
            title="React Scheduler Docs"
            description="Data-Centric React Components for Bootstrap and Material-UI"
          />
          <LinkCard
            link={"https://github.com/HugoChollet/bsporttest"}
            title="Source Code"
            description="Learn how this Agenda Dashboard was made"
          />
        </div>
      </main>
    </>
  );
}
